# Generated by Django 4.0.4 on 2022-05-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0002_remove_entregable_id_remove_estudiante_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('nombre', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('camada', models.IntegerField()),
            ],
        ),
    ]
